-- Manual Migration: Recreate enums to match Zoho CRM values
-- This script recreates all enums with new Zoho-compatible values

BEGIN;

-- ===== 1. LeadSource Enum =====
-- Create new enum type with Zoho values
CREATE TYPE "LeadSource_new" AS ENUM (
  'NONE',
  'PERFORMANCE_MARKETING',
  'ADVERTISEMENT',
  'COLD_CALL',
  'EMPLOYEE_REFERRAL',
  'EXTERNAL_REFERRAL',
  'ONLINESTORE',
  'PARTNER',
  'PUBLIC_RELATIONS',
  'SALES_MAIL_ALIAS',
  'SEMINAR_PARTNER',
  'SEMINAR_INTERNAL',
  'TRADE_SHOW',
  'WEB_DOWNLOAD',
  'WEB_RESEARCH',
  'CHAT',
  'TWITTER',
  'FACEBOOK',
  'EDUCATIONAL_FAIRS_EXHIBITIONS',
  'PRESS_PR',
  'SCHOLARSHIP_PROGRAMS',
  'EDUCATIONAL_PORTALS_AGGREGATORS',
  'STUDENT_ALUMNI_NETWORK',
  'COMPETITIONS_CHALLENGES',
  'WORD_OF_MOUTH',
  'INFLUENCERS_CONTENT_CREATORS',
  'WHATSAPP_BOWER_SCHOOL'
);

-- Drop default, alter column type, then set new default
ALTER TABLE "Lead" ALTER COLUMN "leadSource" DROP DEFAULT;

ALTER TABLE "Lead" ALTER COLUMN "leadSource" TYPE "LeadSource_new"
USING (
  CASE "leadSource"::text
    WHEN 'WEBSITE' THEN 'ONLINESTORE'
    WHEN 'GOOGLE_ADS' THEN 'PERFORMANCE_MARKETING'
    WHEN 'FACEBOOK_ADS' THEN 'PERFORMANCE_MARKETING'
    WHEN 'INSTAGRAM_ADS' THEN 'PERFORMANCE_MARKETING'
    WHEN 'LINKEDIN_CAMPAIGNS' THEN 'PERFORMANCE_MARKETING'
    WHEN 'YOUTUBE_ADS' THEN 'PERFORMANCE_MARKETING'
    WHEN 'OFFLINE_ADVERTISEMENT' THEN 'ADVERTISEMENT'
    WHEN 'REFERRAL' THEN 'EXTERNAL_REFERRAL'
    WHEN 'COUNSELOR_SCHOOL_REFERRALS' THEN 'EXTERNAL_REFERRAL'
    WHEN 'WEBSITE_CHATBOT' THEN 'CHAT'
    WHEN 'WHATSAPP_CAMPAIGNS' THEN 'WHATSAPP_BOWER_SCHOOL'
    WHEN 'WEBINARS_VIRTUAL_EVENTS' THEN 'EDUCATIONAL_FAIRS_EXHIBITIONS'
    WHEN 'MASTERCLASS_GUEST_TALKS' THEN 'EDUCATIONAL_FAIRS_EXHIBITIONS'
    WHEN 'NEWSPAPER_MEDIA' THEN 'PRESS_PR'
    WHEN 'EMAIL_MARKETING' THEN 'PERFORMANCE_MARKETING'
    WHEN 'NONE' THEN 'NONE'
    ELSE 'ONLINESTORE' -- Default for any unmapped values
  END::"LeadSource_new"
);

-- Drop old enum and rename new one
DROP TYPE "LeadSource";
ALTER TYPE "LeadSource_new" RENAME TO "LeadSource";

-- Set new default value
ALTER TABLE "Lead" ALTER COLUMN "leadSource" SET DEFAULT 'ONLINESTORE'::"LeadSource";

-- ===== 2. LeadStatus Enum =====
CREATE TYPE "LeadStatus_new" AS ENUM (
  'NONE',
  'INTERESTED',
  'CONTACTED',
  'CONTACT_IN_FUTURE',
  'ATTEMPTED_TO_CONTACT',
  'LOST_LEAD',
  'NOT_INTERESTED',
  'JUNK_LEAD'
);

ALTER TABLE "Lead" ALTER COLUMN "leadStatus" DROP DEFAULT;

ALTER TABLE "Lead" ALTER COLUMN "leadStatus" TYPE "LeadStatus_new"
USING (
  CASE "leadStatus"::text
    WHEN 'QUALIFIED_INTERESTED' THEN 'INTERESTED'
    WHEN 'NOT_REACHABLE' THEN 'ATTEMPTED_TO_CONTACT'
    WHEN 'NOT_ELIGIBLE_NOT_QUALIFIED' THEN 'NOT_INTERESTED'
    WHEN 'INTERESTED' THEN 'INTERESTED'
    WHEN 'CONTACTED' THEN 'CONTACTED'
    WHEN 'CONTACT_IN_FUTURE' THEN 'CONTACT_IN_FUTURE'
    WHEN 'ATTEMPTED_TO_CONTACT' THEN 'ATTEMPTED_TO_CONTACT'
    WHEN 'LOST_LEAD' THEN 'LOST_LEAD'
    WHEN 'NOT_INTERESTED' THEN 'NOT_INTERESTED'
    WHEN 'JUNK_LEAD' THEN 'JUNK_LEAD'
    WHEN 'NONE' THEN 'NONE'
    ELSE 'INTERESTED'
  END::"LeadStatus_new"
);

DROP TYPE "LeadStatus";
ALTER TYPE "LeadStatus_new" RENAME TO "LeadStatus";

ALTER TABLE "Lead" ALTER COLUMN "leadStatus" SET DEFAULT 'INTERESTED'::"LeadStatus";

-- ===== 3. SalesDepartment Enum =====
CREATE TYPE "SalesDepartment_new" AS ENUM (
  'NONE',
  'K12',
  'UG',
  'PG',
  'EDGE_AI_ONLINE_TEAM'
);

ALTER TABLE "Lead" ALTER COLUMN "salesDepartment" DROP DEFAULT;

ALTER TABLE "Lead" ALTER COLUMN "salesDepartment" TYPE "SalesDepartment_new"
USING (
  CASE "salesDepartment"::text
    WHEN 'SEED_K12_TEAM' THEN 'K12'
    WHEN 'BUILD_UG_TEAM' THEN 'UG'
    WHEN 'LEAD_EXECUTIVE_TEAM' THEN 'PG'
    WHEN 'K12' THEN 'K12'
    WHEN 'UG' THEN 'UG'
    WHEN 'PG' THEN 'PG'
    WHEN 'EDGE_AI_ONLINE_TEAM' THEN 'EDGE_AI_ONLINE_TEAM'
    WHEN 'NONE' THEN 'NONE'
    ELSE 'NONE'
  END::"SalesDepartment_new"
);

DROP TYPE "SalesDepartment";
ALTER TYPE "SalesDepartment_new" RENAME TO "SalesDepartment";

ALTER TABLE "Lead" ALTER COLUMN "salesDepartment" SET DEFAULT 'NONE'::"SalesDepartment";

-- ===== 4. ProgramInterested Enum =====
CREATE TYPE "ProgramInterested_new" AS ENUM (
  'NONE',
  'SRI_SAI_KOLLURU',
  'RAHUL_BHARADWAJ',
  'LEAD_VENTURE_BUILDING',
  'LEAD_VENTURE_CAPITAL_PRIVATE_EQUITY',
  'SEED_WEEKEND_SCHOOL',
  'SEED_SUMMER_CAMP',
  'SEED_WINTER_CAMP',
  'SEED_B2B'
);

ALTER TABLE "Lead" ALTER COLUMN "programInterested" DROP DEFAULT;

ALTER TABLE "Lead" ALTER COLUMN "programInterested" TYPE "ProgramInterested_new"
USING (
  CASE "programInterested"::text
    WHEN 'BUILD_BBA_ENTREPRENEURSHIP' THEN 'NONE'
    WHEN 'BUILD_BTECH_TECHNOLOGY' THEN 'NONE'
    WHEN 'SRI_SAI_KOLLURU' THEN 'SRI_SAI_KOLLURU'
    WHEN 'RAHUL_BHARADWAJ' THEN 'RAHUL_BHARADWAJ'
    WHEN 'LEAD_VENTURE_BUILDING' THEN 'LEAD_VENTURE_BUILDING'
    WHEN 'LEAD_VENTURE_CAPITAL_PRIVATE_EQUITY' THEN 'LEAD_VENTURE_CAPITAL_PRIVATE_EQUITY'
    WHEN 'SEED_WEEKEND_SCHOOL' THEN 'SEED_WEEKEND_SCHOOL'
    WHEN 'SEED_SUMMER_CAMP' THEN 'SEED_SUMMER_CAMP'
    WHEN 'SEED_WINTER_CAMP' THEN 'SEED_WINTER_CAMP'
    WHEN 'SEED_B2B' THEN 'SEED_B2B'
    WHEN 'NONE' THEN 'NONE'
    ELSE 'NONE'
  END::"ProgramInterested_new"
);

DROP TYPE "ProgramInterested";
ALTER TYPE "ProgramInterested_new" RENAME TO "ProgramInterested";

ALTER TABLE "Lead" ALTER COLUMN "programInterested" SET DEFAULT 'NONE'::"ProgramInterested";

-- ===== 5. LeadSubStatus Enum =====
CREATE TYPE "LeadSubStatus_new" AS ENUM (
  'NONE',
  'ENROLLED_IN_CURRENT_BATCH',
  'ENROLLED_IN_UPCOMING_BATCH',
  'PAYMENT_PENDING',
  'DOCUMENTS_PENDING',
  'AWAITING_DECISION',
  'ON_WAITLIST'
);

ALTER TABLE "Lead" ALTER COLUMN "leadSubStatus" DROP DEFAULT;

ALTER TABLE "Lead" ALTER COLUMN "leadSubStatus" TYPE "LeadSubStatus_new"
USING (
  CASE "leadSubStatus"::text
    WHEN 'ALREADY_ENROLLED_OTHER_INSTITUTE' THEN 'NONE'
    WHEN 'APPLICATION_SHARED' THEN 'NONE'
    WHEN 'LEAD_REQUESTED_MORE_INFO' THEN 'NONE'
    WHEN 'ENROLLED_IN_CURRENT_BATCH' THEN 'ENROLLED_IN_CURRENT_BATCH'
    WHEN 'ENROLLED_IN_UPCOMING_BATCH' THEN 'ENROLLED_IN_UPCOMING_BATCH'
    WHEN 'PAYMENT_PENDING' THEN 'PAYMENT_PENDING'
    WHEN 'DOCUMENTS_PENDING' THEN 'DOCUMENTS_PENDING'
    WHEN 'AWAITING_DECISION' THEN 'AWAITING_DECISION'
    WHEN 'ON_WAITLIST' THEN 'ON_WAITLIST'
    WHEN 'NONE' THEN 'NONE'
    ELSE 'NONE'
  END::"LeadSubStatus_new"
);

DROP TYPE "LeadSubStatus";
ALTER TYPE "LeadSubStatus_new" RENAME TO "LeadSubStatus";

ALTER TABLE "Lead" ALTER COLUMN "leadSubStatus" SET DEFAULT 'NONE'::"LeadSubStatus";

COMMIT;
